/* CHECKLIST CONCATENADO*/

		SELECT  C.CRITERIO,TIPO,SUM ( SLA) AS SLA,
				STUFF( ( SELECT ',' + ACAO
					FROM ARQ.CHECKLIST R
					WHERE R.CRITERIO = C.CRITERIO
					FOR XML PATH('')),1,1,'')
				AS ACAO
				INTO ARQ.CHECKLIST_CONCAT
				FROM ARQ.CHECKLIST C
				GROUP BY C.CRITERIO,C.TIPO
				
				
	
	
	/* CONCATENANDO AS NOTAS DO  ANALITICO*/
	
	SELECT NUMERO_MUDANCA,
	   NOTA_FACES = 'NOTA QUALIDADE : ' +  CAST (NOTA_QUALIDADE AS VARCHAR) + ',' + ' '+ 'NOTA RISCO : ' +  CAST (NOTA_RISCO AS VARCHAR) + ','  + ' '
					 + 'NOTA IMPACTO : ' +  CAST (NOTA_IMPACTO AS VARCHAR),
		NOTA_FINAL, ESTEIRA,TIPO,REPUTACAO,BACKLEVEL,HORARIO,QTD_ICS
		INTO #TMP_ANALITICO
		FROM ARQ.ANALITICO 
		WHERE TIPO_MUDANCA = 'EMERGENCIAL' AND STATUS ='PENDAPROV' OR
			  TIPO_MUDANCA IN ('PLANEJADA','NAO PLANEJADA','REPLANEJADA') AND STATUS = 'EMANALISE'
			  
			  
	/* JOIN COM CHECKLIST */
	
	SELECT NUMERO_MUDANCA,NOTA_FACES,NOTA_FINAL,ESTEIRA,ACAO,SLA 
    INTO #TMP_ARQ
	FROM #TMP_ANALITICO T
    INNER JOIN ARQ.CHECKLIST_CONCAT C
	ON T.TIPO = C.TIPO
	WHERE C.CRITERIO = T.REPUTACAO OR C.CRITERIO = T.BACKLEVEL OR C.CRITERIO = T.HORARIO
	
	/* ADICIONAR AS ACOES */
	
	  SELECT NUMERO_MUDANCA,NOTA_FINAL,ESTEIRA,NOTA_FACES,SUM(SLA) AS SLA,
         STUFF((
				SELECT ',' + ACAO
				FROM #TMP_ARQ R
				WHERE R.NUMERO_MUDANCA = C.NUMERO_MUDANCA
				FOR XML PATH('')),1,1,'')
				AS ACAO
				INTO #TMP_ACAO
				FROM #TMP_ARQ C
				GROUP BY NUMERO_MUDANCA,NOTA_FINAL,ESTEIRA,NOTA_FACES	
				
				
				
	 /* ADICIONAR AS NOTAS */
	 
		   SELECT NUMERO_MUDANCA,NOTA_FINAL,ESTEIRA,  SLA = ROUND(((C.SLA / 420) + 2),0) ,
         STUFF((
				SELECT ',' + NOTA_FACES + ' ' + 'ACOES : ' + ACAO
				FROM #TMP_ACAO R 
				WHERE R.NUMERO_MUDANCA = C.NUMERO_MUDANCA
				FOR XML PATH('')),1,1,'')
				AS ACAO
				INTO #TMP_PREP
				FROM #TMP_ACAO C
				GROUP BY NUMERO_MUDANCA,NOTA_FINAL,ESTEIRA,SLA	
				
				
				
	/* TABELA FINAL */
	
	        SELECT NUMERO_MUDANCA AS WONUM
			,NOTA_FINAL AS NOTA_CUBO,
			  ESTEIRA AS ESTEIRA_CUBO
			  ,CAST (SLA AS nvarchar) AS SLA
			  ,ACAO AS LONG_DESCRIPTION
   INTO STAGE.ARQ_CUBO