/* ADD COLUMN*/

ALTER TABLE IMPACTO ADD NOTA_HE NUMERIC (18,2)
ALTER TABLE IMPACTO ADD HI VARCHAR (5)
ALTER TABLE IMPACTO ADD HF VARCHAR (5)


/*HORARIO EXECUCAO*/
 SELECT NUMERO_MUDANCA,HORARIO,INICIO_PROGRAMADO,TERMINO_PROGRAMADO,NOTA,CRITERIO,
    CAST(INICIO_PROGRAMADO AS TIME(4)) 'HORA_INICIO',
	 CAST(TERMINO_PROGRAMADO AS TIME(4)) 'HORA_FIM'
	INTO TESTE
	FROM IMPACTO
	INNER JOIN CRITERIO
	ON HORARIO = CRITERIO


UPDATE IMPACTO SET HI = HORA_INICIO, HF = HORA_FIM
	FROM IMPACTO UPD
	INNER JOIN TESTE T
	ON UPD.NUMERO_MUDANCA = T.NUMERO_MUDANCA

UPDATE IMPACTO SET NOTA_HE = NOTA
	FROM IMPACTO UPD
	INNER JOIN TESTE T
	ON UPD.NUMERO_MUDANCA = T.NUMERO_MUDANCA
	WHERE HI BETWEEN '04:59 ' AND '22:59'
	OR H


/*DELETA TABELA */
DROP TABLE TESTE



/*SELEC*/

SELECT * FROM IMPACTO
SELECT * FROM TESTE

/*DROP COLUMN*/

ALTER TABLE IMPACTO DROP COLUMN HI
ALTER TABLE IMPACTO DROP COLUMN HF
ALTER TABLE IMPACTO DROP COLUMN NOTA_HE

